### ISSUE TITLE
动态修改分页触发点击页码事件

### ISSUE THREAD

**Issue by ChenYCL** [lucky51/am-pagination#1]
你好，如何避免
jQuery('.rderch').on('click',function(){
        var rdrOpts={
             totals:100,/*optional*/  //default:current totals
             pageSize:10,/*optional*/ //default:current pageSize
             page:2/*optional*/ //default:current selected page
          }
        pger.render(rdrOpts);
 });
修改完成 如何避免触发  am.pagination.change监听得事件

**Comment by ghgithub** [comment]
试着用这个取消这个监听事件看看  jQuery('#ampager').off('am.pagination.change',function(e){
                      console.info('jquery bind event :selected page:'+e.page+'  current pageSize:'+e.pageSize+'  number of items'+e.totals);

                });

**Comment by ChenYCL** [comment]
最终解决使用 jQuery('#ampager').off('click') 生效
